[package]
name = "my-amethyst-project"
version = "0.1.0"
authors = ["derelbenkoenig <derelbenkoenig@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }

