name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO these were all needed for amethyst, some may not be for bevy though
      - name: install dependencies
        run: |
          sudo apt install \
          gcc \
          pkg-config \
          openssl \
          libasound2-dev \
          cmake \
          build-essential \
          python3 \
          libfreetype6-dev \
          libexpat1-dev \
          libxcb-composite0-dev \
          libssl-dev \
          libx11-dev \
          libudev-dev
#     # TODO make tests work, switch back to cargo test
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Build & Test
        run: cargo +nightly build --verbose

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly rust
        run: rustup toolchain install nightly
#     # TODO make tests work, switch back to cargo test
      - name: Build & Test
        run: cargo +nightly build --verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#     # TODO make tests work, switch back to cargo test
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Build & Test
        run: cargo +nightly build --verbose
